#!/bin/sh
#
# @name hepia Believer
#
# @type Plane V-Tail
# @class Plane
#
# @output MAIN1 aileron left
# @output MAIN2 aileron right
# @output MAIN3 v-tail left
# @output MAIN4 v-tail right
# @output MAIN5 throttle left
# @output MAIN6 throttle right
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Thierry Bujard <thierry.bujard@hesge.ch>
#
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.fw_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_AUX_RATE 50
	param set PWM_RATE 50
fi

# Configure this as plane
set MAV_TYPE 1

# use our custom mixer
set MIXER believer
